# Generated by Django 3.1.2 on 2021-01-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20201230_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='ShippingTime',
            new_name='shipping_time',
        ),
    ]
